### PR TITLE
chore(sst): upgrade to 4.17.1 and enable state.retention

### PR DESCRIPTION
**Pull request by poysama**
Bumps sst 4.14.1 to 4.17.1 across all three pins (`package.json`, `packages/scripts/package.json`, `apps/client/package.json`) and turns on `state.retention: 30`.

## Why

SST keeps every noncurrent version of the mutable current-state object forever. Measured on 2026-08-04, `app/bike4mind/dev.json` alone held 621,505 noncurrent versions / 8.51 TiB . 31% of the entire dev state bucket. `app/bike4mind/production.json` held 120,579 versions / 1.25 TiB, essentially the whole prod bucket.

`state.retention` (sst/sst#6925) deletes by explicit S3 VersionId, which actually frees bytes. The June prune attempt used `aws s3 rm`, which on a versioned bucket only writes a delete marker and frees zero . that is why it went quiet without shrinking anything. Pruning runs after each successful update for the deploying stage, so two deploys reclaim roughly 9.76 TiB.

Note that `snapshot/` and `eventlog/` are immutable (one key per update) and therefore have zero noncurrent versions on a deploy-only stage. Any verification via `aws s3 ls` is blind to this entire finding . measurement has to use `list-object-versions`.

## state.purge is deliberately narrower than the permanent-stage list

`purge` fires on a successful `sst remove` with zero resources left, and runs SST's `Purge()`: it deletes the stage's secrets AND its encryption passphrase, unrecoverably (upstream flag, sst/sst#6593). Today's default is `Cleanup()`, which only drops eventlog and snapshot . the delta is exactly secrets plus passphrase.

`dev` is the shared STAGING box (`isStagingStage` and `PRODUCTION_STAGES` in `infra/constants.ts`), so it is excluded from purge even though `sst remove` is not blocked there. Only genuinely ephemeral stages . personal stages and `pr####` previews . are purgeable. `removal` and `protect` behaviour is unchanged; those keep the existing `['production', 'shared-dev']` list.

The ~9.76 TiB reclaim comes entirely from `retention`, not from `purge`, so narrowing purge costs nothing against the headline number.

## Merge order

This has to land BEFORE the four premium-overlay pin bumps: Bike4Mind/b4m-overwatch#86, Bike4Mind/b4m-libreoncology#65, Bike4Mind/b4m-pi#10, Bike4Mind/b4m-tavern#43.

Overlay CI composes against this repo at `main`. While main is on 4.14.1 and the overlay branch is on 4.17.1, two sst versions land in one workspace and the `Resource` augmentation declaring `MONGODB_URI` attaches to a different module instance than the overlay imports . all four are currently red with `TS2339: Property 'MONGODB_URI' does not exist on type 'Resource'`. They go green once this merges. This repo's own CI never hydrates real overlays, so it is green independently.

Bike4Mind/bike4mind-deployer#82 is the guard for the drift window: it fails the deploy fast if two sst versions are present in one workspace, instead of surfacing as a cryptic "does not match the sst cli version" about 30 minutes into a deploy.

### CODE REVIEW

**Review by onoya — APPROVED** [review]
LGTM. 🚀

The safety-critical bit is the `purge`/`permanent` split, and it holds up: I grepped every stage-name literal in `infra/` + `sst.config.ts`, and the only long-lived stages are `production`, `shared-dev`, and `dev` — all three excluded from `purge`, so the unrecoverable secrets+passphrase wipe can only ever fire on personal/`pr####` stages. `'staging'`/`'prod'` are just a comment and a WAF suffix, not real stages.

`permanent` → `removal: retain`/`protect: true` is identical to the old inline arrays, so nothing shifts for the protected stages, and all three pins + the lockfile move 4.14.1 → 4.17.1 consistently. Confirmed `state.retention: 30` against SST's docs — it's a snapshot count that prunes after each successful update. The one thing I couldn't check from here is the actual byte reclaim; that only shows after ~2 real deploys, so worth an eyeball with `list-object-versions` (not `aws s3 ls`, per your note) once prod deploys twice.

The inline rationale on why `dev` is excluded despite `sst remove` not being blocked is exactly what stops someone from "simplifying" the two lists back together and nuking staging's secrets six months from now. Nice.

(Tiny non-blocker: the `retention: 30` comment reads in TiB/versions but the `30` is a snapshot count — "last 30 snapshots" would kill the ambiguity.)
